server:
  port: 8080


spring:
  rabbitmq:
    username: community
    password: community
    virtual-host: /community
    host: localhost
    port: 5672
    publisher-returns: true
    publisher-confirm-type: correlated


  redis:
    host: localhost
    port: 6379

  datasource:
    username: root
    password: li13526282136
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community_new?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai

  elasticsearch:
    username: elastic
    uris: http://localhost:9201

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mail:
    host: smtp.qq.com
    port: 587
    protocol: smtp
    username: 1148205230@qq.com
    password: nmozukqkrxvaihea



front: http://localhost:8000
front_test: http://localhost:8001

jwtKey: 123456

storage:
  user:
    avatar: "/Users/plixiaofei/Documents/Program/Project/community-new/avatar/"
  questionImg: "/Users/plixiaofei/Documents/Program/Project/community-new/questionImg/"


rabbitmq:
  notify:
    exchange:
      at.exchange
    queue:
      at: at.queue
      reply: at.reply

mail:
  from: 1148205230@qq.com
  to: 1148205230@qq.com
  list:
    rabbitmq-at:
      "服务器管理 - 消息队列 @ 相关"

page:
  question: 8
  notification: 10